spring:
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.43.50:3306/scm_water
    username: root
    password: 911816
  thymeleaf:
    cache: false
logging:
  level: 
    mapper: debug    